set nocompatible

call plug#begin('~/.vim/plugged')
Plug 'chriskempson/base16-vim'

Plug 'kien/ctrlp.vim'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-fugitive'
Plug 'ciaranm/detectindent'

Plug 'justinmk/vim-syntax-extra'
Plug 'tpope/vim-markdown'
Plug 'fatih/vim-go'
Plug 'rust-lang/rust.vim'
Plug 'xolox/vim-misc'
Plug 'xolox/vim-lua-ftplugin'
call plug#end()

set guioptions=gmtr
set number
set statusline=%<%f\ %h%m%r%=%-20.(line=%l,col=%c%V,totlin=%L%)\%h%m%r%=%-40(,bytval=0x%B,%n%Y%)\%P
set wildignore=*.o,*.obj,*.bak,*.exe,*.pyc,*.DS_Store,*.db
set nobackup
set noswapfile

map ,v :sp ~/.vim/vimrc<cr> " edit my .vimrc file in a split
map ,e :e ~/.vim/vimrc<cr>      " edit my .vimrc file
map ,u :source ~/.vim/vimrc<cr> " update the system settings from my vimrc file

nnoremap ,r :%s/\<<C-r><C-w>\>//g<Left><Left>

let g:ctrlp_lazy_update = 150
let g:ctrlp_split_window = 0
let g:ctrlp_working_path_mode = 0
let g:ctrlp_persistent_input = 0
let g:ctrlp_match_window_reversed = 0

nnoremap <Leader>t :CtrlP<cr>
nnoremap <Leader>e :CtrlPBuffer<cr>

let g:go_def_mapping_enabled = 1

au FileType go nmap <Leader>gd <Plug>(go-doc)
au FileType go nmap <Leader>gs <Plug>(go-implements)
au FileType go nmap <Leader>gi <Plug>(go-info)
au FileType go nmap <Leader>gr <Plug>(go-rename)
au FileType go nmap <Leader>gg <Plug>(go-def)
au FileType go nnoremap <Leader>y :GoDecls<cr>

set t_Co=256
set background=dark
if has('nvim')
	set termguicolors
end
colorscheme base16-google-light
set guifont=Consolas\ 10

autocmd FileType sh,python,markdown setlocal expandtab autoindent
autocmd FileType html,ruby,javascript,coffee,lua setlocal expandtab autoindent tabstop=2 shiftwidth=2 softtabstop=2

nnoremap <Leader>g :Ggrep!<Space>
autocmd QuickFixCmdPost *grep* cwindow

set tabstop=4
set shiftwidth=4
set softtabstop=4
